#
# Makefile for the sensors drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_CORE)		+= sensors_core.o
obj-$(CONFIG_SENSORS_L3GD20)		+= l3gd20_gyro.o
obj-$(CONFIG_SENSORS_LSM303DLHC)	+= lsm303dlhc_m.o lsm303dlhc_a.o
obj-$(CONFIG_SENSORS_LPS331)		+= lps331ap.o
#obj-$(CONFIG_SENSORS_LIS303D_I2C)	+= lis3dh_acc.o
